import React, { useEffect, useState } from 'react'
import { createRoot } from 'react-dom/client'
import './styles.css'

const portraitUrl = `${import.meta.env.BASE_URL}Rahul%20Verma.png`

const experience = [
  { year: '2023 — Present', company: 'JBM Group', role: 'Assistant Manager', location: 'Gurugram, India', points: ['Created detailed commercial offers, including welding process and robotic calculation.', 'Handled customer technical discussions and settlement of business terms.', 'Managed project cash flow to ensure profitability and delivery milestones.', 'Improvement in existing weld lines including cycle time improvement and automation level.', 'Coordinated with purchasing department to finalize commercial and technical project requirements with suppliers.', 'Responsible for achieving business profitability targets in line with unit budget.'] },
  { year: '2020 — 2023', company: 'Samgo Engineering Pvt. Ltd.', role: 'Senior Engineer', location: 'India', points: ['Prepared techno-commercial offers and welding process for 2W, BIW and chassis assembly.', 'Prepared cash outflow for welding fixtures and integration.', 'Designed welding processes for 2W, BIW and chassis assemblies.', 'Executed project timelines and supervised implementation of welding fixtures.'] },
  { year: '2018 — 2020', company: 'Arvind Engineers', role: 'Design Engineer (Mechanical)', location: 'India', points: ['Designed spot and MIG welding fixtures using Unigraphics (NX).', 'Liaised with clients to ensure quality delivery and feedback alignment.', 'Oversaw full responsibility for project design and execution.'] },
  { year: '2016 — 2018', company: 'Tokai Engineering Pvt. Ltd.', role: 'Design Engineer (Mechanical)', location: 'India', points: ['Drafted 3D models and designs in AutoCAD for jigs, SPMs and panel checkers.', 'Developed concepts for jigs, fixtures, checking fixtures, Special Purpose Machines (SPM), and panel checkers.'] }
]
const expertise = ['Welding Fixture Design', 'Welding Process Design', 'Robotic Welding Calculation', 'Techno-Commercial Offers', 'Project Costing', 'Project Coordination']
const business = ['Marketing', 'Marketing Strategy', 'Market Research & Analysis', 'Customer Relationship', 'Cash Flow & Project Costing', 'Supplier Coordination']
const tools = ['NX Unigraphics', 'AutoCAD', 'MS Excel', 'PowerPoint']
const resumeExperience = [
  { company: 'JBM Group', role: 'Assistant Manager', years: '2023 – Present', bullets: ['Created commercial offers with welding process and robotic calculations.', 'Handled customer technical discussions, business terms and project cash flow.', 'Coordinated suppliers and purchasing; supported weld-line, cycle-time and automation improvements.'] },
  { company: 'Samgo Engineering Pvt. Ltd.', role: 'Senior Engineer', years: '2020 – 2023', bullets: ['Prepared techno-commercial offers and welding processes for 2W, BIW and chassis assemblies.', 'Prepared cash outflow for welding fixtures and integration; executed timelines and fixture implementation.'] },
  { company: 'Arvind Engineers', role: 'Design Engineer (Mechanical)', years: '2018 – 2020', bullets: ['Designed spot and MIG welding fixtures using Unigraphics (NX).', 'Coordinated with clients and oversaw project design and execution.'] },
  { company: 'Tokai Engineering Pvt. Ltd.', role: 'Design Engineer (Mechanical)', years: '2016 – 2018', bullets: ['Drafted 3D models and designs in AutoCAD for jigs, SPMs and panel checkers.', 'Developed concepts for jigs, fixtures, checking fixtures, SPMs and panel checkers.'] }
]

function Icon({ children }) { return <span className="icon" aria-hidden="true">{children}</span> }
function SectionLabel({ number, children }) { return <div className="section-label"><span>{number}</span>{children}</div> }
function Navbar({ onDownload }) {
  const [open, setOpen] = useState(false)
  const links = [['About', 'about'], ['Experience', 'experience'], ['Expertise', 'expertise'], ['Education', 'education'], ['Contact', 'contact']]
  return <header className="nav-wrap"><nav className="nav shell"><a className="brand" href="#home" onClick={() => setOpen(false)}><span>RV</span><span>Rahul Verma</span></a><button className="menu" onClick={() => setOpen(!open)} aria-label="Toggle navigation" aria-expanded={open}>☰</button><div className={`nav-links ${open ? 'open' : ''}`}>{links.map(([label, id]) => <a key={id} href={`#${id}`} onClick={() => setOpen(false)}>{label}</a>)}<button className="nav-cta" onClick={onDownload}>Download resume <span>↓</span></button></div></nav></header>
}
function Hero({ onDownload, isDownloading }) { return <section className="hero" id="home"><div className="hero-grid shell"><div className="hero-copy"><div className="eyebrow"><i /> Automotive Engineering · Project Management</div><h1>Rahul<br /><em>Verma.</em></h1><h2 className="hero-role">Assistant Manager</h2><p className="hero-lede">Automotive engineering professional specializing in welding fixture design, techno-commercial proposals, welding processes, project coordination and customer engagement.</p><div className="hero-actions"><a className="button primary" href="#experience">View my experience <span>↗</span></a><button className="button secondary" onClick={onDownload}>{isDownloading ? 'Preparing resume…' : 'Download resume ↓'}</button><a className="resume-link" href="#contact">LinkedIn / Contact ↗</a></div><div className="stats"><div><strong>8.10+</strong><span>Years experience</span></div><div><strong>2016</strong><span>Career start</span></div><div><strong>Automotive</strong><span>Industry</span></div></div></div><div className="portrait-wrap"><div className="portrait-frame"><img src={portraitUrl} alt="Rahul Verma in a navy suit" /></div><div className="portrait-note">01 <span>/</span> BUILT FOR IMPACT</div><div className="orbit orbit-a" /><div className="orbit orbit-b" /></div></div><div className="hero-bottom shell"><span>Scroll to explore</span><span className="scroll-line" /><span>01 — 07</span></div></section> }
function About() { return <section className="section about shell" id="about"><div className="section-head"><SectionLabel number="01">Profile</SectionLabel><h2>Technical depth.<br /><em>Commercial clarity.</em></h2></div><div className="about-content"><p className="intro">Assistant Manager with over 8.10 years of experience in the automotive industry, specializing in welding fixture design, project management, and marketing.</p><p>From developing welding processes and robotic calculations to coordinating suppliers and settling business terms, Rahul works across the full project lifecycle with a focus on practical delivery.</p><div className="focus-grid"><div><span>01</span><h3>Technical</h3><p>Fixture design, welding processes and robotic calculations.</p></div><div><span>02</span><h3>Business</h3><p>Techno-commercial proposals, costing and commercial discussions.</p></div><div><span>03</span><h3>Project</h3><p>Execution, cash flow, supplier coordination and milestones.</p></div></div></div></section> }
function Experience() { return <section className="section dark-section" id="experience"><div className="shell"><div className="section-head split"><div><SectionLabel number="02">Experience</SectionLabel><h2>A career built<br /><em>on the floor.</em></h2></div><p>Four roles. One consistent thread: turning engineering intent into dependable production outcomes.</p></div><div className="timeline">{experience.map((item, i) => <article className="timeline-item" key={item.company}><div className="timeline-marker">{String(i + 1).padStart(2, '0')}</div><div className="timeline-meta"><span>{item.year}</span><small>{item.location}</small></div><div className="timeline-card"><div className="card-top"><div><h3>{item.company}</h3><p>{item.role}</p></div><span className="arrow">↗</span></div><ul>{item.points.map(point => <li key={point}>{point}</li>)}</ul></div></article>)}</div></div></section> }
function Expertise() { return <><section className="section shell" id="expertise"><div className="section-head split"><div><SectionLabel number="03">Expertise</SectionLabel><h2>The toolkit to<br /><em>move work forward.</em></h2></div><p>Capabilities shaped by hands-on design, commercial responsibility and project execution.</p></div><div className="expertise-grid">{expertise.map((item, i) => <div className="expertise-card" key={item}><span className="card-number">0{i + 1}</span><Icon>{['⌘', '◌', '◈', '▱', '∿', '→'][i]}</Icon><h3>{item}</h3><span className="card-arrow">↗</span></div>)}</div></section><section className="business-band"><div className="shell business-layout"><div><SectionLabel number="04">Business & Commercial</SectionLabel><h2>Engineering that<br /><em>understands business.</em></h2></div><div className="business-grid">{business.map((item, i) => <div key={item}><span>0{i + 1}</span><h3>{item}</h3></div>)}</div></div></section><section className="tools shell"><div><SectionLabel number="05">Engineering toolkit</SectionLabel><h2>Tools of the<br /><em>trade.</em></h2></div><div className="tool-list">{tools.map((tool, i) => <div className="tool" key={tool}><span>0{i + 1}</span><strong>{tool}</strong><span>↗</span></div>)}</div></section></> }
function Education() { return <section className="section education" id="education"><div className="shell"><div className="section-head split"><div><SectionLabel number="06">Education</SectionLabel><h2>Always in<br /><em>motion.</em></h2></div><p>Formal training that pairs mechanical engineering foundations with an ongoing focus on marketing.</p></div><div className="education-grid"><article><span className="edu-year">2025</span><div><h3>MBA – Marketing</h3><p>Amity University, Greater Noida</p><span className="status">Pursuing <b>·</b> Grade: 7.0/10</span></div></article><article><span className="edu-year">2016</span><div><h3>B.Tech – Mechanical Engineering</h3><p>Amity University</p></div></article></div><div className="personal"><div><h3>Languages</h3><div className="pill-row"><span>English</span><span>Hindi</span><span>German</span></div></div><div><h3>Outside work</h3><div className="pill-row"><span><Icon>✈</Icon> Traveling</span><span><Icon>◉</Icon> Cricket</span></div></div></div></div></section> }
function Contact() { return <section className="contact" id="contact"><div className="shell contact-inner"><div><SectionLabel number="07">Contact</SectionLabel><h2>Let’s make the<br /><em>next move.</em></h2><p>For professional conversations, engineering projects and business opportunities.</p></div><div className="contact-links"><a href="tel:+919599242504"><Icon>↗</Icon><span><small>Call</small>+91 959 924 2504</span><b>↗</b></a><a href="mailto:rahulverma611994@gmail.com"><Icon>✉</Icon><span><small>Email</small>rahulverma611994@gmail.com</span><b>↗</b></a><a href="https://www.linkedin.com/in/rahul-verma-1b1649140" target="_blank" rel="noreferrer"><Icon>in</Icon><span><small>LinkedIn</small>linkedin.com/in/rahul-verma-1b1649140</span><b>↗</b></a></div></div></section> }
async function imageDataUrl(url) { const response = await fetch(url); const blob = await response.blob(); return await new Promise((resolve, reject) => { const reader = new FileReader(); reader.onloadend = () => resolve(reader.result); reader.onerror = reject; reader.readAsDataURL(blob) }) }
function addPdfText(pdf, text, x, y, width, size = 8.2, color = [48, 60, 76], lineGap = 3.7) { pdf.setFontSize(size); pdf.setTextColor(...color); const lines = pdf.splitTextToSize(text, width); pdf.text(lines, x, y); return y + lines.length * lineGap }
async function generateResume() {
  const { jsPDF } = await import('jspdf')
  const pdf = new jsPDF({ unit: 'mm', format: 'a4', compress: true }); const W = 210; const margin = 14; let y = 15
  pdf.setFillColor(11, 20, 36); pdf.rect(0, 0, W, 47, 'F');
  try { const photo = await imageDataUrl(portraitUrl); pdf.addImage(photo, 'PNG', 174, 11, 22, 28, undefined, 'FAST') } catch { /* Resume remains complete if the portrait is unavailable. */ }
  pdf.setTextColor(255,255,255); pdf.setFont('helvetica', 'bold'); pdf.setFontSize(24); pdf.text('RAHUL VERMA', margin, y + 8); pdf.setFont('helvetica', 'normal'); pdf.setFontSize(10); pdf.setTextColor(222,228,235); pdf.text('Assistant Manager  |  Automotive Engineering', margin, y + 16); pdf.setFontSize(7.4); pdf.text('+91 959 924 2504  |  rahulverma611994@gmail.com', margin, y + 26); pdf.text('linkedin.com/in/rahul-verma-1b1649140  |  Gurugram, India', margin, y + 32)
  y = 58; const section = (title) => { pdf.setFont('helvetica','bold'); pdf.setFontSize(9); pdf.setTextColor(201,110,61); pdf.text(title.toUpperCase(), margin, y); pdf.setDrawColor(218,220,216); pdf.line(margin, y + 2, W - margin, y + 2); y += 8 }
  section('Professional Summary'); y = addPdfText(pdf, 'Assistant Manager with over 8.10 years of experience in the automotive industry, specializing in welding fixture design, project management and marketing. Expertise includes techno-commercial offers, welding process optimization, robotic welding calculations, customer relationship management and cash flow analysis.', margin, y, W - margin * 2, 8.2, [48,60,76], 3.8); y += 5
  section('Core Expertise'); y = addPdfText(pdf, 'Welding Fixture Design  •  Welding Process Design  •  Spot Welding  •  MIG Welding  •  Manual Welding  •  Techno-Commercial Proposal Development  •  Robotic Time & Cost Calculation  •  Project Coordination  •  Customer Interaction  •  Marketing Strategy  •  Market Research & Analysis  •  Cash Flow & Project Costing', margin, y, W - margin * 2, 8.1, [48,60,76], 3.7); y += 5
  section('Professional Experience');
  resumeExperience.forEach(item => { pdf.setFont('helvetica','bold'); pdf.setFontSize(10); pdf.setTextColor(17,28,45); pdf.text(item.company, margin, y); pdf.setFont('helvetica','normal'); pdf.setFontSize(8); pdf.setTextColor(105,116,132); pdf.text(`${item.role}  |  ${item.years}`, W - margin, y, { align: 'right' }); y += 4.5; item.bullets.forEach(bullet => { y = addPdfText(pdf, `• ${bullet}`, margin + 2, y, W - margin * 2 - 4, 7.8, [67,78,93], 3.4); y += 1 }); y += 3 })
  section('Education'); pdf.setFont('helvetica','bold'); pdf.setFontSize(9); pdf.setTextColor(17,28,45); pdf.text('MBA – Marketing', margin, y); pdf.setFont('helvetica','normal'); pdf.setFontSize(8); pdf.setTextColor(85,96,111); pdf.text('Amity University, Greater Noida  |  2025  |  PURSUING  |  Grade: 7.0/10', W - margin, y, { align: 'right' }); y += 5; pdf.setFont('helvetica','bold'); pdf.setFontSize(9); pdf.setTextColor(17,28,45); pdf.text('B.Tech – Mechanical Engineering', margin, y); pdf.setFont('helvetica','normal'); pdf.setFontSize(8); pdf.setTextColor(85,96,111); pdf.text('Amity University  |  2016', W - margin, y, { align: 'right' }); y += 9
  section('Tools & Languages'); y = addPdfText(pdf, 'NX Unigraphics  •  AutoCAD  •  MS Excel  •  PowerPoint  |  English  •  Hindi  •  German', margin, y, W - margin * 2, 8.2, [48,60,76], 3.8)
  pdf.setFont('helvetica','normal'); pdf.setFontSize(7); pdf.setTextColor(140,147,153); pdf.text('Rahul Verma  |  Assistant Manager · Automotive Engineering', margin, 288); pdf.text('rahulverma611994@gmail.com', W - margin, 288, { align: 'right' }); pdf.save('Rahul_Verma_Resume.pdf')
}
function App() { const [isDownloading, setIsDownloading] = useState(false); const onDownload = async () => { if (isDownloading) return; setIsDownloading(true); try { await generateResume() } finally { setIsDownloading(false) } }; useEffect(() => { document.documentElement.style.scrollBehavior = 'smooth'; return () => { document.documentElement.style.scrollBehavior = 'auto' } }, []); return <><Navbar onDownload={onDownload} /><div className="sr-only" aria-live="polite">{isDownloading ? 'Preparing resume' : ''}</div><main><Hero onDownload={onDownload} isDownloading={isDownloading} /><About /><Experience /><Expertise /><Education /><Contact /></main><footer><div className="shell"><div className="brand"><span>RV</span><span>Rahul Verma</span></div><p>Assistant Manager · Automotive Engineering</p><div className="footer-right"><a href="https://www.linkedin.com/in/rahul-verma-1b1649140" target="_blank" rel="noreferrer">LinkedIn ↗</a><a href="mailto:rahulverma611994@gmail.com">Email ↗</a><span>© {new Date().getFullYear()} Rahul Verma</span></div></div></footer></> }

createRoot(document.getElementById('root')).render(<App />)
